require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TeamOutcomesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # TeamOutcome. As you add validations to TeamOutcome, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TeamOutcomesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all team_outcomes as @team_outcomes" do
      team_outcome = TeamOutcome.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:team_outcomes)).to eq([team_outcome])
    end
  end

  describe "GET #show" do
    it "assigns the requested team_outcome as @team_outcome" do
      team_outcome = TeamOutcome.create! valid_attributes
      get :show, {:id => team_outcome.to_param}, valid_session
      expect(assigns(:team_outcome)).to eq(team_outcome)
    end
  end

  describe "GET #new" do
    it "assigns a new team_outcome as @team_outcome" do
      get :new, {}, valid_session
      expect(assigns(:team_outcome)).to be_a_new(TeamOutcome)
    end
  end

  describe "GET #edit" do
    it "assigns the requested team_outcome as @team_outcome" do
      team_outcome = TeamOutcome.create! valid_attributes
      get :edit, {:id => team_outcome.to_param}, valid_session
      expect(assigns(:team_outcome)).to eq(team_outcome)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new TeamOutcome" do
        expect {
          post :create, {:team_outcome => valid_attributes}, valid_session
        }.to change(TeamOutcome, :count).by(1)
      end

      it "assigns a newly created team_outcome as @team_outcome" do
        post :create, {:team_outcome => valid_attributes}, valid_session
        expect(assigns(:team_outcome)).to be_a(TeamOutcome)
        expect(assigns(:team_outcome)).to be_persisted
      end

      it "redirects to the created team_outcome" do
        post :create, {:team_outcome => valid_attributes}, valid_session
        expect(response).to redirect_to(TeamOutcome.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved team_outcome as @team_outcome" do
        post :create, {:team_outcome => invalid_attributes}, valid_session
        expect(assigns(:team_outcome)).to be_a_new(TeamOutcome)
      end

      it "re-renders the 'new' template" do
        post :create, {:team_outcome => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested team_outcome" do
        team_outcome = TeamOutcome.create! valid_attributes
        put :update, {:id => team_outcome.to_param, :team_outcome => new_attributes}, valid_session
        team_outcome.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested team_outcome as @team_outcome" do
        team_outcome = TeamOutcome.create! valid_attributes
        put :update, {:id => team_outcome.to_param, :team_outcome => valid_attributes}, valid_session
        expect(assigns(:team_outcome)).to eq(team_outcome)
      end

      it "redirects to the team_outcome" do
        team_outcome = TeamOutcome.create! valid_attributes
        put :update, {:id => team_outcome.to_param, :team_outcome => valid_attributes}, valid_session
        expect(response).to redirect_to(team_outcome)
      end
    end

    context "with invalid params" do
      it "assigns the team_outcome as @team_outcome" do
        team_outcome = TeamOutcome.create! valid_attributes
        put :update, {:id => team_outcome.to_param, :team_outcome => invalid_attributes}, valid_session
        expect(assigns(:team_outcome)).to eq(team_outcome)
      end

      it "re-renders the 'edit' template" do
        team_outcome = TeamOutcome.create! valid_attributes
        put :update, {:id => team_outcome.to_param, :team_outcome => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested team_outcome" do
      team_outcome = TeamOutcome.create! valid_attributes
      expect {
        delete :destroy, {:id => team_outcome.to_param}, valid_session
      }.to change(TeamOutcome, :count).by(-1)
    end

    it "redirects to the team_outcomes list" do
      team_outcome = TeamOutcome.create! valid_attributes
      delete :destroy, {:id => team_outcome.to_param}, valid_session
      expect(response).to redirect_to(team_outcomes_url)
    end
  end

end
